name: Test Integration
on: push

jobs:
  test-integration-api:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Integration
        run: make test-integration-api
